; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
boards_dir = boards

[env]
; platform = https://github.com/pioarduino/platform-espressif32#54.03.20
platform = https://github.com/pioarduino/platform-espressif32#55.03.34
framework = arduino
build_flags =
    -D USE_LITTLE_FS=1
    -D CONFIG_ARDUHAL_ESP_LOG=1
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
    -D SNMP_VECTOR=1
    -D SNMP_STREAM=0
board_build.filesystem = littlefs
monitor_speed=115200
monitor_filters = default, esp32_exception_decoder
;lib_compat_mode = strict
;lib_ldf_mode = chain
lib_deps =
    bblanchon/ArduinoJson@^7.4.1
    https://github.com/BwanaFr/ESP32PingMs.git#ESP32Log
    https://github.com/BwanaFr/SNMP.git
;   https://github.com/h2zero/OneWire.git#GPIO-fix
;   milesburton/DallasTemperature@^4.0.4

extra_scripts =
    pre:./scripts/make_content.py   ;Make HTML static content
    pre:./scripts/make_version.py   ;Make Git version
    post:./scripts/make_fw_file.py  ;Output firmware file

[env:waveshare_esp32_eth_full]
board = waveshare-esp32-eth
build_flags =
    ${env.build_flags}
    -D RGB_LED_PIN=21
; Remove the COLOR compatibility to avoid conflicts with FastLed
    -D NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY=1
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SSD1306@^2.5.15

[env:waveshare_esp32_eth_full_oled13]
board = waveshare-esp32-eth
build_flags =
    ${env.build_flags}
    -D RGB_LED_PIN=21
; Remove the COLOR compatibility to avoid conflicts with FastLed
    -D NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY=1
    -D SH110X=1
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SH110X@^2.1.14

[env:waveshare_esp32_eth_basic]
board = waveshare-esp32-eth
build_flags =
    ${env.build_flags}
    -D RGB_LED_PIN=21
    -D NO_SCREEN=1
lib_deps =
    ${env.lib_deps}

[env:waveshare_esp32_eth_ch1115]
board = waveshare-esp32-eth
build_flags =
    ${env.build_flags}
    -D RGB_LED_PIN=21
; Remove the COLOR compatibility to avoid conflicts with FastLed
    -D NO_ADAFRUIT_SSD1306_COLOR_COMPATIBILITY=1
    -D CH1115=1
lib_deps =
    ${env.lib_deps}
    https://github.com/BwanaFr/OLED_CH1115.git